DROP TABLE items;
DROP TABLE orders;
DROP TABLE users;

CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, price integer);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT, item_id integer, user_id integer);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);


INSERT INTO items(name, price) VALUES('TOVAR', 200);
INSERT INTO items(name, price) VALUES('ROVAT', 400);